spring:
  application:
    name: spring-observability-micrometer-prom
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
  observations:
    annotations:
      enabled: true     
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
        
logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"   
      
      