spring:
  application:
    name: saga-service-A
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: svc1
      properties:
        spring:
          json:
            trusted-packages: com.soham.selfteaching.springboot.txn.saga1.entity.*
            
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: soham
    password: india123
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update