spring:
  application:
    name: employee-mngment-backend
  data:
    rest:
      base-path: /data
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: soham
    password: india123
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp  