server:
  port: 9090
spring:
  application:
    name: employee-mngment-backend
  profiles:
    active:
    - dev
  config:
    import:
    - optional:configserver:http://localhost:8888
  cloud:
    config:
      username: admin
      password: oracle
  data:
    rest:
      base-path: /data
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: soham
    password: india123
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
eureka.client.service-url.defaultZone: http://localhost:8761/eureka/        