server:
  port: 8761
spring:
  application:
    name: spring-cloud-service-registry
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    
  server:
    enable-self-preservation: true      
